AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS ParallelCluster serverless API for AWS Batch
Globals:
  Function:
    Timeout: 900

Resources:
  ParallelClusterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: parallelcluster_function/
      Handler: function.lambda_handler
      Runtime: python3.7
      Policies:
      - Statement:
        - Sid: EC2Describe
          Effect: Allow
          Action:
          - ec2:DescribeKeyPairs
          - ec2:DescribeRegions
          - ec2:DescribeVpcs
          - ec2:DescribeSubnets
          - ec2:DescribeSecurityGroups
          - ec2:DescribePlacementGroups
          - ec2:DescribeImages
          - ec2:DescribeInstances
          - ec2:DescribeInstanceStatus
          - ec2:DescribeSnapshots
          - ec2:DescribeVolumes
          - ec2:DescribeVpcAttribute
          - ec2:DescribeAddresses
          - ec2:CreateTags
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeAvailabilityZones
          Resource: '*'
        - Sid: EC2LaunchTemplate
          Effect: Allow
          Action:
          - ec2:CreateLaunchTemplate
          - ec2:ModifyLaunchTemplate
          - ec2:DeleteLaunchTemplate
          - ec2:DescribeLaunchTemplates
          - ec2:DescribeLaunchTemplateVersions
          Resource: '*'
        - Sid: NetworkingEasyConfig
          Effect: Allow
          Action:
          - ec2:CreateVpc
          - ec2:ModifyVpcAttribute
          - ec2:DescribeNatGateways
          - ec2:CreateNatGateway
          - ec2:DescribeInternetGateways
          - ec2:CreateInternetGateway
          - ec2:AttachInternetGateway
          - ec2:DescribeRouteTables
          - ec2:CreateRouteTable
          - ec2:AssociateRouteTable
          - ec2:CreateSubnet
          - ec2:ModifySubnetAttribute
          Resource: '*'
        - Sid: EC2Modify
          Effect: Allow
          Action:
          - ec2:CreateVolume
          - ec2:RunInstances
          - ec2:AllocateAddress
          - ec2:AssociateAddress
          - ec2:AttachNetworkInterface
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:CreateNetworkInterface
          - ec2:CreateSecurityGroup
          - ec2:ModifyVolumeAttribute
          - ec2:ModifyNetworkInterfaceAttribute
          - ec2:DeleteNetworkInterface
          - ec2:DeleteVolume
          - ec2:TerminateInstances
          - ec2:DeleteSecurityGroup
          - ec2:DisassociateAddress
          - ec2:RevokeSecurityGroupIngress
          - ec2:RevokeSecurityGroupEgress
          - ec2:ReleaseAddress
          - ec2:CreatePlacementGroup
          - ec2:DeletePlacementGroup
          Resource: '*'
        - Sid: DynamoDB
          Effect: Allow
          Action:
          - dynamodb:DescribeTable
          - dynamodb:CreateTable
          - dynamodb:DeleteTable
          - dynamodb:TagResource
          Resource: 'arn:aws:dynamodb:<REGION>:<AWS ACCOUNT ID>:table/parallelcluster-*'
        - Sid: CloudFormation
          Effect: Allow
          Action:
          - cloudformation:DescribeStackEvents
          - cloudformation:DescribeStackResource
          - cloudformation:DescribeStackResources
          - cloudformation:DescribeStacks
          - cloudformation:ListStacks
          - cloudformation:GetTemplate
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:UpdateStack
          Resource: 'arn:aws:cloudformation:<REGION>:<AWS ACCOUNT ID>:stack/parallelcluster-*'
        - Sid: SQS
          Effect: Allow
          Action:
          - sqs:GetQueueAttributes
          - sqs:CreateQueue
          - sqs:SetQueueAttributes
          - sqs:DeleteQueue
          - sqs:TagQueue
          Resource: '*'
        - Sid: SQSQueue
          Effect: Allow
          Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:ChangeMessageVisibility
          - sqs:DeleteMessage
          - sqs:GetQueueUrl
          Resource: 'arn:aws:sqs:<REGION>:<AWS ACCOUNT ID>:parallelcluster-*' 
        - Sid: SNS
          Effect: Allow
          Action:
          - sns:ListTopics
          - sns:GetTopicAttributes
          - sns:CreateTopic
          - sns:Subscribe
          - sns:DeleteTopic
          Resource: '*' 
        - Sid: IAMRole
          Effect: Allow
          Action:
          - iam:PassRole
          - iam:CreateRole
          - iam:DeleteRole
          - iam:GetRole
          - iam:TagRole
          - iam:SimulatePrincipalPolicy
          Resource:
          - arn:aws:iam::<AWS ACCOUNT ID>:role/parallelcluster-*
        - Sid: IAMInstanceProfile
          Effect: Allow
          Action:
          - iam:CreateInstanceProfile
          - iam:DeleteInstanceProfile
          - iam:GetInstanceProfile
          - iam:PassRole
          Resource: 'arn:aws:iam::<AWS ACCOUNT ID>:instance-profile/*'  
        - Sid: IAM
          Effect: Allow
          Action:
          - iam:AddRoleToInstanceProfile
          - iam:RemoveRoleFromInstanceProfile
          - iam:GetRolePolicy
          - iam:GetPolicy
          - iam:AttachRolePolicy
          - iam:DetachRolePolicy
          - iam:PutRolePolicy
          - iam:DeleteRolePolicy
          Resource: '*' 
        - Sid: S3ResourcesBucket
          Effect: Allow
          Action:
          - s3:*
          Resource: 'arn:aws:s3:::parallelcluster-*'
        - Sid: S3ParallelClusterReadOnly
          Effect: Allow
          Action:
          - s3:Get*
          - s3:List*
          Resource: 'arn:aws:s3:::<REGION>-aws-parallelcluster/*'  
        - Sid: Lambda
          Effect: Allow
          Action:
          - lambda:CreateFunction
          - lambda:DeleteFunction
          - lambda:GetFunctionConfiguration
          - lambda:InvokeFunction
          - lambda:AddPermission
          - lambda:RemovePermission
          Resource: 'arn:aws:lambda:<REGION>:<AWS ACCOUNT ID>:function:parallelcluster-*'
        - Sid: Logs
          Effect: Allow
          Action:
          - logs:*
          Resource: 'arn:aws:logs:<REGION>:<AWS ACCOUNT ID>:*' 
        - Sid: CodeBuild
          Effect: Allow
          Action:
          - codebuild:*
          Resource: 'arn:aws:codebuild:<REGION>:<AWS ACCOUNT ID>:project/parallelcluster-*'
        - Sid: ECR
          Effect: Allow
          Action:
          - ecr:*
          Resource: '*'
        - Sid: Batch
          Effect: Allow
          Action:
          - Batch:*
          Resource: '*'
        - Sid: AmazonCloudWatchEvents
          Effect: Allow
          Action:
          - events:*
          Resource: '*'
      Events:
        pCluster:
          Type: Api
          Properties:
            Path: /pcluster
            Method: any

Outputs:
  ParallelClusterApi:
    Description: "API Gateway endpoint URL for Prod stage for ParallelCluster function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pcluster/"
